Feat: Update profile service
TTFM-Labs/user-service pull request #10
Opened 2020-11-24 16:19 UTC by mariusjagminas

2020-11-24 16:31 UTC, kowalski requested changes
I haven't seen tests for this new endpoint. Perhaps you forgotten to add those to commit?

2020-11-24 16:31 UTC, kowalski commented on src/users/userProfile.entity.ts
> +  @Column()
all these string columns should have `{ default: '' }` as options.

This way in migration you will create these as:

```
"firstName" character varying NOT NULL DEFAULT ''
```

as opposed to:
```
"firstName" character varying NOT NULL
```
which you have currently.

This will allow you to create an entry without needed to specify all the parameters which you don't happen to have

2020-11-24 16:31 UTC, kowalski commented on src/users/user.interface.ts
> +export class ProfileDto {
It would be easier to have all fields optional, to not force frontend to send artificial values

2020-11-24 16:31 UTC, kowalski commented on src/users/users.service.ts
> +      return { updatedAt: record.updatedAt };
It's nice for frontend to just return the full record from a POST.

2020-11-24 16:31 UTC, kowalski commented on src/users/users.controller.ts
> +  @Post('profile')
should this be `PATCH` not `POST`?

2020-11-25 08:51 UTC, kowalski commented on src/migrations/1606240649168-CreateUserProfiles.ts
> +    await queryRunner.query(
These changes on emailVerification.code looks suspicious. Have you been changing code around this? Sadly typeorm sometimes incorrectly detects change in column definition and needlesly adds code to migrations. Please double check and perhapd remove these 2 lines (and from down migration respectively)

2020-11-25 08:52 UTC, kowalski commented on src/migrations/1606240752043-CreateAdditionalEmails.ts
> +      `COMMENT ON COLUMN "emailVerifications"."code" IS NULL`,
Here its repeated

2020-11-25 08:54 UTC, kowalski commented on src/users/user.interface.ts
> +  avatarUrl: string;
It will not be url. We will just have some set of avatars hardcoded in frontend. Here we will just store the id of it (as understood by the frontend)

2020-11-25 08:57 UTC, kowalski requested changes
Please check comments. Also I'm still not finding a test case that updates user profile.

2020-11-25 09:04 UTC, mariusjagminas commented on src/migrations/1606240649168-CreateUserProfiles.ts
> +    await queryRunner.query(
Yes, it looks weird. I will check on it.

2020-11-25 09:05 UTC, mariusjagminas commented on src/users/user.interface.ts
> +  avatarUrl: string;
I'll change it to id.

2020-11-25 09:06 UTC, mariusjagminas commented
I'm working on tests right now, I thought to submit it as separate PR

2020-11-25 10:44 UTC, kowalski approved these changes

2020-11-25 11:32 UTC, merged