Feat: mobile auth
TTFM-Labs/user-service pull request #17
Opened 2020-12-04 14:45 UTC by mariusjagminas

2020-12-04 15:00 UTC, kowalski requested changes

2020-12-04 15:00 UTC, kowalski commented on src/phone-auth/phone-auth.guard.ts
> +const SMS_CODE_EXPIRATION = 60 * 1000;
1 minutes is a short time :) give it 10 maybe?

2020-12-04 15:00 UTC, kowalski commented on src/users/user.entity.ts
> +  codeGeneratedAt: string;
this field represents a date so it should be stored as date in database (not string)

```
  @CreateDateColumn({ nullable: true })
  public codeGeneratedAt: Date;
```

```
import {
  CreateDateColumn,
  ...
} from 'typeorm';

2020-12-04 15:00 UTC, kowalski commented on src/phone-auth/phone-auth.controller.ts
> +  @Post('sign-up')
I would prefer this endpoint to be called something like "send-code"

2020-12-04 15:00 UTC, kowalski commented on src/phone-auth/phone-auth.interface.ts
> +  @IsMobilePhone()
I think the right validator here is:
```
@IsPhoneNumber('ZZ')
```

source: https://github.com/typestack/class-validator

2020-12-04 15:00 UTC, kowalski commented on src/phone-auth/phone-auth.interface.ts
> +  @IsMobilePhone()
also I I'm not sure if you don't need to combine it with "@IsNotEmpty()".

2020-12-04 15:03 UTC, mariusjagminas commented on src/phone-auth/phone-auth.guard.ts
> +const SMS_CODE_EXPIRATION = 60 * 1000;
ok iI will

2020-12-04 15:05 UTC, mariusjagminas commented on src/users/user.entity.ts
> +  codeGeneratedAt: string;
Yep. That should be date

2020-12-04 15:09 UTC, mariusjagminas commented on src/phone-auth/phone-auth.controller.ts
> +  @Post('sign-up')
ok. What about 'phone-auth' , maybe 'mobile-auth' would be a better name?

2020-12-04 15:12 UTC, mariusjagminas commented on src/phone-auth/phone-auth.interface.ts
> +  @IsMobilePhone()
I will check that

2020-12-04 15:20 UTC, kowalski commented on src/phone-auth/phone-auth.controller.ts
> +  @Post('sign-up')
hmm, this endpoints sends a code to a given number
it's all it does 
I would just call it 'send-code', really

2020-12-04 15:21 UTC, kowalski commented on src/phone-auth/phone-auth.controller.ts
> +  @Post('sign-up')
phone-auth is already the route of the controller, so the whole path becomes
/phone-auth/send-code

2020-12-04 15:27 UTC, mariusjagminas commented on src/phone-auth/phone-auth.interface.ts
> +  @IsMobilePhone()
@IsMobilePhone () is a valid validator, it also checks that it is not empty.

2020-12-04 15:33 UTC, mariusjagminas commented on src/phone-auth/phone-auth.controller.ts
> +  @Post('sign-up')
so probably `/phone-auth/log-in` route  should be renamed as  `verify-code`

2020-12-04 15:35 UTC, kowalski commented on src/phone-auth/phone-auth.interface.ts
> +  @IsMobilePhone()
but does @IsMobilePhone() enforce that the country code is present ? So like +48 XXX XXX XXX (X)?

2020-12-04 15:36 UTC, kowalski commented on src/phone-auth/phone-auth.controller.ts
> +  @Post('sign-up')
yes, I like it

2020-12-07 11:03 UTC, kowalski approved these changes
Note for next work:

We are now removing phoneNumber from user profile. We probably should add it back in GET request, but not in PATCH request. I think the in GET we should return email and phoneNumber of the user. Just not support changing it in PATCH.

2020-12-07 11:13 UTC, merged