Feature: Forgot password flow
TTFM-Labs/user-service pull request #34
Opened 2020-12-30 15:03 UTC by mariusjagminas

2020-12-30 15:19 UTC, kowalski requested changes

2020-12-30 15:19 UTC, kowalski commented on src/email-verification/emailVerification.templates.ts
> +                        <a href="${webAppBaseUrl}/reset-password?token=${tokenUri}&id=${id}"
Don't use query string, instead put the params into path. 

This is important for ios guys. Through deeplinking they can get params from path, but not from query string.

2020-12-30 15:19 UTC, kowalski commented on src/users/users.service.ts
> +      throw new NotFoundException(MSG.EMAIL_NOT_FOUND);
You are assuming here that all the possible errors are caused of wrong email. That's a bit of  a stretch. I can think different reasons for this to fail, yet here we are swallowing the original error and just returning 404

2020-12-30 15:25 UTC, mariusjagminas commented on src/users/users.service.ts
> +      throw new NotFoundException(MSG.EMAIL_NOT_FOUND);
I did that intentionally for security reasons. I think that here we should return only the generic message, without any explicit explanation what happened.?

2020-12-31 09:42 UTC, kowalski commented on src/users/users.service.ts
> +      throw new BadRequestException();
You are swallowing original error. At least log it. Swallowing errors leads to long unhappy hours of debugging in future

2020-12-31 10:15 UTC, kowalski approved these changes

2020-12-31 10:16 UTC, merged