Feature: Sign up flow step 1
TTFM-Labs/user-service pull request #4
Opened 2020-11-20 15:11 UTC by mariusjagminas

2020-11-20 15:16 UTC, kowalski commented on package.json
> +    "aws-sdk": "^2.795.0",
This has to be done a little bit diffently. 
Please install aws-sdk globally in Dockerfile and make sure that paths are set so that app reaches this.

Please see how it's done in verifiid.


Reason: aws-sdk is a huge package (like 50MB). We are going to deploy this as Lambda and Lambda execution environment provides aws-sdk pre-installed globally. Therefore you only need to specify it in package.json as peerDependency. This reduces the bundle size by like 60%, which is very important for the startup time

2020-11-20 15:17 UTC, kowalski commented on src/email-verification/email-verification.service.spec.ts
> +  it('should be defined', () => {
don't add files like this to the repo. If you don't end up modyfing tests for services, remove them.

2020-11-20 15:19 UTC, kowalski commented on src/email-verification/email-verification.service.ts
> +    return await this.emailService.emailUser(
you haven't declared return type of `addToTable` method, so I'm guessing it's `Promise<void>`

Instead of 
```
return await this.emailService.emailUser(
```
do 
```
await this.emailService.emailUser( )
```

Alternatively if `emailUser()` returns something please declare this as return type of `addToTable()` in line 22

2020-11-20 15:20 UTC, kowalski commented on src/email-verification/email-verification.service.ts
> +  async getStatus(email: string) {
Declare return value `Promise<what?>`

2020-11-20 15:22 UTC, kowalski commented on src/email-verification/email-verification.service.ts
> +    const { status } = await this.emailVerification.findOne({ email });
This can potentially fail, right?
`fineOne` is not guaranteed to give an instance. If there is no instance there will not `null` returned which you're trying to desctruct. 

I'm surprised typescript didn't catch this.

Correct way:

```
const record = await this.emailVerification.findOne({ email });
return record?.status;
```

2020-11-20 15:22 UTC, kowalski commented on src/email-verification/emailVerification.entity.ts
> +@Entity({ name: 'email verification' })
'email verification' is not a nice name for a table.

I'd use `emailVerification`. Please be sure to update this in migration as well.

2020-11-20 15:23 UTC, kowalski commented on src/email-verification/emailVerification.entity.ts
> +@Entity({ name: 'email verification' })
actually `emailVerifications`. table names are always plurar form

2020-11-20 15:23 UTC, kowalski commented on src/email/email.service.spec.ts
> +import { Test, TestingModule } from '@nestjs/testing';
empty file from generator, remove tihs

2020-11-20 15:24 UTC, kowalski commented on src/migrations/1605867947220-CreateEmailValidation.ts
> +        await queryRunner.query(`CREATE TABLE "email verification" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "status" character varying NOT NULL, "code" character varying NOT NULL DE
"email verification" -> "emailVerifications"

2020-11-20 15:24 UTC, kowalski commented on src/users/user.entity.ts
> +@Entity({ name: 'user' })
"user" -> "users"

2020-11-20 15:25 UTC, kowalski commented on src/migrations/1605799512590-CreateUser.ts
> +      `CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NU
"user" -> "users"

2020-11-20 15:25 UTC, kowalski commented on src/users/users.module.ts
> +import { EmailVerificationModule } from 'src/email-verification/email-verification.module';
don't import using `src/...` this will fail when compiled to dist.

Import as relative:
```
import { EmailVerificationModule } from '../email-verification/email-verification.module';
```

2020-11-20 15:26 UTC, kowalski commented on src/users/users.service.ts
> +import { EmailVerificationService } from 'src/email-verification/email-verification.service';
change to relative import

2020-11-20 15:27 UTC, kowalski commented on src/email-verification/email-verification.service.ts
> +  async addToTable(dto: SignUpDto, id: number) {
from `dto` you only use `dto.email`. Maybe simplify and just accept `email: string` in this function?

2020-11-20 15:28 UTC, kowalski commented on src/email-verification/email-verification.service.ts
> +  async addToTable(dto: SignUpDto, id: number) {
I don't like `addToTable` name. It does much more than adding record to table.

I would call this `sendEmailVerification`

2020-11-20 15:29 UTC, kowalski requested changes
Please see the comments

2020-11-20 15:45 UTC, mariusjagminas commented on src/email-verification/email-verification.service.ts
> +    const { status } = await this.emailVerification.findOne({ email });
Yes it's working. Yes I've to take more care when destructing objects from db

2020-11-20 15:47 UTC, mariusjagminas commented on src/users/users.module.ts
> +import { EmailVerificationModule } from 'src/email-verification/email-verification.module';
Yes it does, also it fails in test environment too.

2020-11-20 15:53 UTC, mariusjagminas commented on src/email-verification/email-verification.service.ts
> +  async addToTable(dto: SignUpDto, id: number) {
It doing 2 operations, so maybe something like `handleSigUpFlow` ?

2020-11-20 15:54 UTC, kowalski commented on src/email-verification/email-verification.service.ts
> +  async addToTable(dto: SignUpDto, id: number) {
`handleVerificationFlow` ? 
Motivation: Email verification could later be used when changing email, not necessarily on signup

2020-11-23 08:59 UTC, kowalski approved these changes

2020-11-23 09:03 UTC, merged